import test from 'node:test';
import assert from 'node:assert/strict';
import {COINS,ENEMIES,createRun,currentEnemy,playCoin,getIntent,getEnemyStatus,resolveEnemy,nextTurn,nextCombat} from '../dist/combat.mjs';
function setup(id){const s=createRun();s.order=[id,...s.order.filter(x=>x!==id)];s.enemy=currentEnemy(s).hp;return s;}
function hand(s,faces){s.coins=faces.map(([effect,value])=>({id:Math.random(),name:'Test',faces:[[effect,value],['defense',3]],face:0,used:false}));}
function end(s){const events=resolveEnemy(s);nextTurn(s);return events;}
test('each run has five unique encounters and four unique coins per draw',()=>{const orders=new Set();for(let n=0;n<30;n++){const s=createRun();assert.equal(new Set(s.order).size,5);assert.deepEqual([...s.order].sort(),ENEMIES.map(e=>e.id).sort());assert.equal(new Set(s.coins.map(c=>c.id)).size,4);orders.add(s.order.join(','));}assert.ok(orders.size>1);assert.equal(COINS.length,7);});
test('Captain preserves attack 5 / guard 6 cycle',()=>{const s=setup('captain');assert.equal(getIntent(s).value,5);end(s);assert.equal(s.hp,23);assert.equal(getIntent(s).kind,'block');end(s);assert.equal(s.enemyBlock,6);assert.equal(getIntent(s).value,5);});
test('Gunner telegraphs a free load before fire 10 and recovery shot 3',()=>{const s=setup('gunner');assert.equal(getIntent(s).kind,'load');end(s);assert.equal(s.hp,28);assert.equal(getIntent(s).value,10);end(s);assert.equal(s.hp,18);assert.equal(getIntent(s).value,3);end(s);assert.equal(s.hp,15);assert.equal(getIntent(s).kind,'load');});
test('Ironjaw bash changes with remaining block, expires after calculated hit',()=>{const s=setup('ironjaw');end(s);assert.equal(s.enemyBlock,8);assert.equal(getIntent(s).value,12);hand(s,[['attaque',6]]);playCoin(s,0);assert.equal(s.enemy,36);assert.equal(s.enemyBlock,2);assert.equal(getIntent(s).value,6);end(s);assert.equal(s.hp,22);assert.equal(s.enemyBlock,0);});
test('Duelist riposte lasts one player turn and respects player block',()=>{const s=setup('duelist');end(s);assert.equal(getIntent(s).kind,'riposte');end(s);assert.equal(s.riposte,true);assert.equal(getIntent(s).value,7);assert.equal(getEnemyStatus(s),'RIPOSTE 2');hand(s,[['defense',3],['attaque',6]]);playCoin(s,0);const hp=s.hp;const events=playCoin(s,1);assert.ok(events.some(x=>x.type==='riposte'));assert.equal(s.hp,hp);assert.equal(s.block,1);end(s);assert.equal(s.riposte,false);assert.equal(s.hp,hp-6);});
test('a killing blow prevents riposte; a lethal counter ends the run',()=>{const s=setup('duelist');s.riposte=true;s.enemy=4;hand(s,[['attaque',6]]);playCoin(s,0);assert.equal(s.hp,28);assert.equal(s.outcome,'combatVictory');const t=setup('duelist');t.riposte=true;t.hp=1;hand(t,[['attaque',3]]);playCoin(t,0);assert.equal(t.outcome,'defeat');assert.equal(t.defeated,0);});
test('Baron requires eight HP damage in the fuse window, not damage into block',()=>{const s=setup('baron');hand(s,[['attaque',6]]);playCoin(s,0);end(s);assert.equal(s.turnDamage,0);assert.equal(getIntent(s).value,12);s.enemyBlock=2;hand(s,[['attaque',6],['attaque',3]]);playCoin(s,0);playCoin(s,1);assert.equal(s.turnDamage,7);assert.equal(getIntent(s).value,12);assert.equal(getEnemyStatus(s),'1 HP TO INTERRUPT');s.actions=1;hand(s,[['attaque',1]]);playCoin(s,0);assert.equal(getIntent(s).kind,'cancelled');const hp=s.hp;end(s);assert.equal(s.hp,hp);assert.equal(getIntent(s).value,6);});
test('uninterrupted Baron explodes and returns to fuse after saber strike',()=>{const s=setup('baron');end(s);end(s);assert.equal(s.hp,16);assert.equal(getIntent(s).value,6);end(s);assert.equal(s.hp,10);assert.equal(getIntent(s).kind,'fuse');});
test('Momentum grants actions next turn, never immediately; flip costs only source action',()=>{const s=setup('gunner');hand(s,[['actions',2],['retournement',1],['attaque',5]]);playCoin(s,0);assert.equal(s.actions,1);assert.equal(s.nextActions,2);playCoin(s,1);assert.equal(s.actions,0);assert.equal(s.target,true);playCoin(s,2);assert.equal(s.coins[2].face,1);assert.equal(s.actions,0);assert.equal(s.target,false);end(s);assert.equal(s.actions,4);assert.equal(s.nextActions,0);});
test('transitions preserve HP, clear temporary states; victory only after all five',()=>{const s=createRun();const order=[...s.order];s.hp=17;for(let i=0;i<5;i++){s.enemy=1;s.actions=2;hand(s,[['attaque',6]]);playCoin(s,0);assert.equal(s.defeated,i+1);assert.equal(s.outcome,i===4?'victory':'combatVictory');assert.equal(s.order[s.encounter],order[i]);if(i<4){s.block=9;s.enemyBlock=3;s.nextActions=2;s.riposte=true;assert.equal(nextCombat(s),true);assert.equal(s.hp,17);assert.equal(s.block,0);assert.equal(s.enemyBlock,0);assert.equal(s.nextActions,0);assert.equal(s.riposte,false);assert.equal(s.actions,2);}else assert.equal(nextCombat(s),false);}});
test('death stops further turns, coin plays and encounter advancement',()=>{const s=setup('captain');s.hp=1;resolveEnemy(s);assert.equal(s.outcome,'defeat');assert.equal(nextTurn(s),false);assert.equal(nextCombat(s),false);assert.deepEqual(playCoin(s,0),[]);});

test('forge offers three distinct upgrades and accepts one empty face only', async()=>{
 const {offerUpgrades,forgeFace}=await import('../dist/combat.mjs');const s=createRun();s.outcome='combatVictory';s.over=true;
 const offers=offerUpgrades(s);assert.equal(new Set(offers.map(u=>u.id)).size,3);assert.deepEqual(offerUpgrades(s),offers);
 assert.equal(forgeFace(s,s.pool[0].id,0,'unknown'),false);assert.equal(forgeFace(s,s.pool[0].id,0,offers[0].id),true);assert.equal(forgeFace(s,s.pool[1].id,0,offers[1].id),false);
 nextCombat(s);assert.equal(s.pool[0].upgrades[0],offers[0].id);assert.equal(createRun().pool[0].upgrades,undefined);
 s.outcome='combatVictory';s.rewardClaimed=false;s.reward=null;const again=offerUpgrades(s);assert.equal(forgeFace(s,s.pool[0].id,0,again[0].id),false);assert.equal(forgeFace(s,s.pool[0].id,1,again[0].id),true);
});
test('attack upgrade resolves as one hit before riposte, and defense can gain attack',()=>{
 const s=createRun();s.enemy=8;s.riposte=true;s.coins=[{faces:[['attaque',6],['defense',3]],face:0,upgrades:['attack',null],used:false}];playCoin(s,0);assert.equal(s.enemy,0);assert.equal(s.hp,28);
 const b=createRun();b.enemy=30;b.coins=[{faces:[['defense',3],['attaque',6]],face:0,upgrades:['balanced',null],used:false}];playCoin(b,0);assert.equal(b.block,4);assert.equal(b.enemy,29);
});
test('action upgrade refunds an action and reroll touches only unplayed coins',()=>{
 const s=createRun();s.coins=[{faces:[['defense',3],['attaque',6]],face:0,upgrades:['action',null],used:false}];playCoin(s,0);assert.equal(s.actions,2);
 const b=createRun();b.coins=[{faces:[['defense',3],['attaque',6]],face:0,upgrades:['reroll',null],used:false},{faces:[['attaque',3],['defense',6]],face:0,used:false},{faces:[['attaque',3],['defense',6]],face:0,used:true}];playCoin(b,0,()=>.9);assert.equal(b.coins[0].face,0);assert.equal(b.coins[1].face,1);assert.equal(b.coins[2].face,0);
});
